sudo: required

language: r

os:
  - linux


# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda3
  - export PATH=/home/travis/miniconda3/bin:$PATH

## Cache R packages
cache: packages


## Set up conda environment and TMB
install:
  - conda create -c conda-forge -n pymb_test -y python=3.6 numpy scipy libiconv libxml2 lxml scikit-sparse
  - source activate pymb_test
  - pip install rpy2
  - R -e 'install.packages("Matrix",  repos="http://cran.us.r-project.org", dependencies=T)'
  - R -e 'install.packages("TMB",  repos="http://cran.us.r-project.org", dependencies=T)'


jobs:
  include:
    - stage: Install PyMB and run examples
      script:
        - bin/01_pymb_install.sh
        - bin/02_pymb_linreg.sh

notifications:
  email:
    on_success: never
    on_failure: never
