sudo: required

language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - export PATH="$HOME/miniconda/bin:$PATH"

apt_packages:
  - wget
  - curl
  - bzip2
  - ca-certificates
  - libglib2.0-0
  - libxext6
  - libsm6
  - libxrender1
  - git
  - gcc
  - g++
  - libreadline-dev
  - tar
  - build-essential

os:
  - linux

cache: packages

jobs:
  include:
    - stage: Set up Python and R environment
      script: 
        - bin/01_set_env.sh
    - stage: Install TMB
      script:
        - bin/02_install_TMB.sh



notifications:
  email:
    on_success: never
    on_failure: never
