sudo: required

language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y \
        wget \
        curl \
        bzip2 \
        ca-certificates \
        libglib2.0-0 \
        libxext6 \
        libsm6 \
        libxrender1 \
        git \
        gcc \
        g++ \
        libreadline-dev \
        tar \
        build-essential
  - sudo apt-get purge
  - sudo apt-get clean
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a


os:
  - linux

cache: packages

jobs:
  include:
    - stage: Set up environment
      python: 3.6
      script: 
        - bin/01_set_env.sh



notifications:
  email:
    on_success: never
    on_failure: never
