sudo: required

services:
  - docker

language: python


cache: packages

os:
  - linux

# apt_packages:
#     - libmetis-dev
#     - libopenblas-dev
#     - liblapack-dev


before_install:
- docker pull continuumio/miniconda3
- docker run  continuumio/miniconda3

jobs:
  include:
    - stage: Set up environment
      script: 
        - bin/01_set_env.sh



notifications:
  email:
    on_success: never
    on_failure: never
