sudo: required

language: r

os:
  - linux

cache: 
  packages
  directories:
    - /home/travis/R-bin/
    - /home/travis/miniconda/

jobs:
  include:
    - stage: Set up Python and R environment
      r: 3.5
      script:
        - bin/01_set_env.sh
        - bin/02_install_TMB.sh
    - stage: Run a TMB test
      r: 3.5
      script:
        - bin/03_example_1.sh


notifications:
  email:
    on_success: never
    on_failure: never
