sudo: required

language: r

os:
  - linux


# Setup anaconda
before_install:
  - sudo apt-get update && sudo apt-get install -y libeigen3-dev
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda3
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - export LD_LIBRARY_PATH=/home/travis/R-bin/lib/R/lib:/home/travis/miniconda3/lib:$LD_LIBRARY_PATH
  - R -e 'install.packages(c("Matrix", "RcppEigen", "numDeriv", "TMB"),  repos="http://cran.us.r-project.org", dependencies=T)'
  - R -e "TMB::runExample('randomregression')"

## Cache R packages
cache: packages

## Set up conda environment, TMB and PyMB
install:
  - conda create -c conda-forge -n pymb_test -y python=3.6 numpy scipy libiconv libxml2 lxml scikit-sparse
  - source activate pymb_test
  - which -a python && pip install rpy2 && python -c "import rpy2.rinterface as rinterface"
  - cd ../PyMB && python setup.py install


jobs:
  include:
    - stage: Run PyMB tests
      script:
        - bin/02_pymb_linreg.sh

notifications:
  email:
    on_success: never
    on_failure: never
