sudo: required

language: r

os:
  - linux

cache: packages


jobs:
  include:
    - stage: Set up Python and R environment
      r: 3.5
      install:
        - bin/01_set_env.sh
        - bin/02_install_TMB.sh
    - stage: Run a TMB test
      r: 3.5
      install: true
      script:
        - bin/03_example_1.sh



notifications:
  email:
    on_success: never
    on_failure: never
