sudo: required

language: r

os:
  - linux


# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda3
  - export PATH=/home/travis/miniconda3/bin:$PATH

## Cache R packages
cache: packages


## Set up conda environment, TMB and PyMB
install:
  - conda create -c conda-forge -n pymb_test -y python=3.6 numpy scipy libiconv libxml2 lxml scikit-sparse
  - source activate pymb_test
  - which -a python && pip install rpy2
  - R -e 'install.packages("Matrix",  repos="http://cran.us.r-project.org", dependencies=T)'
  - R -e 'install.packages("TMB",  repos="http://cran.us.r-project.org", dependencies=T)'
  - cd ../PyMB && python setup.py install && python -c "import rpy2.rinterface as rinterface"


jobs:
  include:
    - stage: Run PyMB tests
      script:
        - bin/02_pymb_linreg.sh

notifications:
  email:
    on_success: never
    on_failure: never
